spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student?zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jdbc:
    template:
      #查询超时，当查询时间超过3秒时，就会查询超时
      query-timeout: 3

#配置mybatis规则
mybatis:
  #config-location: classpath:mybatis/mybatis-config.xml
  #config-location和configuration不能同时存在
  #所以可以不写全局配置文件，所有的配置文件的配置都放在configuration(推荐,这样就不用那个配置文件了)
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    #开启驼峰命名法
    map-underscore-to-camel-case: true